/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package penjualanbarang;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
/**
 *
 * @author Muh Israjab DS
 */
public class penjual extends javax.swing.JFrame {
 private PreparedStatement stat;
    private ResultSet rs;
    private DefaultTableModel model = null;
    koneksi k = new koneksi();
 
    public penjual() {
        initComponents();
         inputId.setVisible(false);
        this.RadioYa.setEnabled(false);
        this.RadioTidak.setEnabled(false);
        this.btnhitung.setEnabled(false);
        k.connect();
       refreshTable();
    }
    public class jual extends penjual{
      int id;
boolean selected;
String kode_barang, nama_barang, jenis_barang, jumlah_barang, harga_satuan, diskon, total_harga, memberYa, memberTidak, member;
public jual() {
    
    this.id = 0;
    this.kode_barang = inputKodeBarang.getText();
    this.nama_barang = inputNamaBarang.getText();
    this.jumlah_barang = inputJumlahBarang.getText();
    this.harga_satuan = inputHargaSatuan.getText();
    this.diskon = inputDiskon.getText();
    this.total_harga = inputTotalHarga.getText();
    
    if (RadioYa.isSelected()) {
        member = "Ya";
        
    } else if (RadioTidak.isSelected()) {
        member = "Tidak";
    }
    
if (CheckMakanan.isSelected()) {
        jenis_barang = "Makanan";
        
    }
   else if (CheckMinuman.isSelected()) {
        jenis_barang = "Minuman";
        
    } else if (CheckATK.isSelected()){
        jenis_barang = "ATK";
        
    }

}

        
    }
      public void refreshTable()
       {
            model = new DefaultTableModel();
            model.addColumn("ID");
            model.addColumn("KODE BARANG");
            model.addColumn("NAMA BARANG");
            model.addColumn("JENIS BARANG");
            model.addColumn("JUMLAH BARANG");
            model.addColumn("HARGA SATUAN");
            model.addColumn("DISKON");
            model.addColumn("TOTAL HARGA");
            model.addColumn("MEMBER");
           tblTransaksi.setModel(model);
           try {
               stat = k.getCon().prepareStatement("SELECT * FROM tbl_transaksi");
               rs = stat.executeQuery();
               while(rs.next()){
                   Object[] data = {
                       rs.getString(1),
                        rs.getString(2),
                         rs.getString(3),
                          rs.getString(4),
                           rs.getString(5),
                            rs.getString(6),
                             rs.getString(7),
                              rs.getString(8),
                               rs.getString(9),
                           
                   };
                   model.addRow(data);
               }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
             btnhitung.setEnabled(false);
          RadioYa.setEnabled(false);
          RadioTidak.setEnabled(false);
          this.buttonGroup2.clearSelection();
          this.buttonGroup1.clearSelection();
           inputId.setText("");
           inputKodeBarang.setText("");
           inputNamaBarang.setText("");
           inputJumlahBarang.setText("");
           inputHargaSatuan.setText("");
           inputDiskon.setText("");
           inputTotalHarga.setText("");
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        inputId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        CheckMakanan = new javax.swing.JCheckBox();
        CheckMinuman = new javax.swing.JCheckBox();
        CheckATK = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        inputHargaSatuan = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        inputJumlahBarang = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        inputKodeBarang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        RadioYa = new javax.swing.JRadioButton();
        RadioTidak = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        inputNamaBarang = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransaksi = new javax.swing.JTable();
        btnhitung = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        inputDiskon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        inputTotalHarga = new javax.swing.JTextField();
        bersihkan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("FORM TRANSAKSI PEMBAYARAN");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Barang : ");

        buttonGroup1.add(CheckMakanan);
        CheckMakanan.setText("Makanan");
        CheckMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMakananActionPerformed(evt);
            }
        });

        buttonGroup1.add(CheckMinuman);
        CheckMinuman.setText("Minuman");
        CheckMinuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMinumanActionPerformed(evt);
            }
        });

        buttonGroup1.add(CheckATK);
        CheckATK.setText("ATK");
        CheckATK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckATKActionPerformed(evt);
            }
        });

        jLabel6.setText("Harga Satuan : ");

        inputHargaSatuan.setEnabled(false);

        jLabel7.setText("Jumlah Barang :");

        inputJumlahBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputJumlahBarangActionPerformed(evt);
            }
        });
        inputJumlahBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inputJumlahBarangKeyReleased(evt);
            }
        });

        jLabel2.setText("kode Barang");

        inputKodeBarang.setEnabled(false);

        jLabel3.setText("Member  :");

        buttonGroup2.add(RadioYa);
        RadioYa.setText("Ya");
        RadioYa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioYaActionPerformed(evt);
            }
        });

        buttonGroup2.add(RadioTidak);
        RadioTidak.setText("Tidak");
        RadioTidak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioTidakActionPerformed(evt);
            }
        });
        RadioTidak.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RadioTidakKeyReleased(evt);
            }
        });

        jLabel4.setText("Nama Barang : ");

        inputNamaBarang.setEnabled(false);

        tblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTransaksi);

        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel8.setText("Diskon          :");

        inputDiskon.setEnabled(false);

        jLabel9.setText("Total Harga :");

        inputTotalHarga.setEnabled(false);
        inputTotalHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTotalHargaActionPerformed(evt);
            }
        });

        bersihkan.setText("Bersihkan");
        bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bersihkanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(686, 686, 686))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(413, 413, 413)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RadioYa)
                                .addGap(44, 44, 44)
                                .addComponent(RadioTidak))
                            .addComponent(inputKodeBarang)
                            .addComponent(inputNamaBarang)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CheckMakanan)
                                .addGap(18, 18, 18)
                                .addComponent(CheckMinuman)
                                .addGap(18, 18, 18)
                                .addComponent(CheckATK))
                            .addComponent(inputHargaSatuan)
                            .addComponent(inputJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(inputDiskon)
                                    .addComponent(inputTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(147, 147, 147))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(186, 186, 186))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(inputKodeBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(RadioYa)
                            .addComponent(RadioTidak))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(inputNamaBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8))
                            .addComponent(inputDiskon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputTotalHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addComponent(btnhitung, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CheckMinuman)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckATK)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(CheckMakanan)))
                        .addGap(20, 20, 20)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputJumlahBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        jual p = new jual();

        try {
            stat = k.getCon().prepareStatement("INSERT INTO tbl_transaksi VALUES (?,?,?,?,?,?,?,?,?)");
            stat.setInt(1,0);
            stat.setString(2, inputKodeBarang.getText());
            stat.setString(3,inputNamaBarang.getText());
            stat.setString(4, p.jenis_barang);
            stat.setString(5, inputJumlahBarang.getText());
            stat.setString(6, inputHargaSatuan.getText());
            stat.setString(7,inputDiskon.getText());
            stat.setString(8, inputTotalHarga.getText());
            stat.setString(9, p.member);
            stat.executeUpdate();
            refreshTable();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI INPUT !");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        try {
            stat = k.getCon().prepareStatement("delete from tbl_transaksi where id= ?");
            stat.setString(1,inputId.getText());
            stat.executeUpdate();
            refreshTable();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI HAPUS !");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void CheckMinumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMinumanActionPerformed
    inputNamaBarang.setText("Fruit Tea");
    inputKodeBarang.setText("MI001");
    inputHargaSatuan.setText("3500");
    }//GEN-LAST:event_CheckMinumanActionPerformed

    private void CheckATKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckATKActionPerformed
       inputNamaBarang.setText("Buku Tulis");
       inputKodeBarang.setText("MA001");
        inputHargaSatuan.setText("12000");
    }//GEN-LAST:event_CheckATKActionPerformed

    private void RadioYaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioYaActionPerformed
     jual p = new jual(); 
     btnhitung.setEnabled(true);
     
      p.diskon = String.valueOf(10*(Integer.parseInt(p.harga_satuan) * Integer.parseInt(p.jumlah_barang))/100);
        inputDiskon.setText(p.diskon);
    }//GEN-LAST:event_RadioYaActionPerformed

    private void RadioTidakKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RadioTidakKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioTidakKeyReleased

    private void tblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTransaksiMouseClicked
        jual p = new jual();
        int selectedRow = tblTransaksi.getSelectedRow();
        TableModel model = tblTransaksi.getModel();
        String jenis = model.getValueAt(selectedRow, 3).toString();
        String members = model.getValueAt(selectedRow, 8).toString();
        
        if(members.equals("Ya")){
            RadioYa.setSelected(true);
        }else{
            RadioTidak.setSelected(true);
        }
        
      switch(jenis){
          case "Makanan" :
              CheckMakanan.setSelected(true);
              CheckMinuman.setSelected(false);
              CheckATK.setSelected(false);
              break;
          case "Minuman" :
              CheckMinuman.setSelected(true);
              CheckATK.setSelected(false);
              CheckMakanan.setSelected(false);
              break;
          case "ATK" :
              CheckATK.setSelected(true);
              CheckMinuman.setSelected(false);
              CheckMakanan.setSelected(false);
              break;
      }
        
        
        RadioYa.setEnabled(true);
        RadioTidak.setEnabled(true);
        
        inputId.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 0).toString());
        inputKodeBarang.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 1).toString());
        inputNamaBarang.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 2).toString());
        inputJumlahBarang.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 4).toString());
        inputHargaSatuan.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 5).toString());
        inputDiskon.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 6).toString());
        inputTotalHarga.setText(model.getValueAt(tblTransaksi.getSelectedRow(), 7).toString());
    }//GEN-LAST:event_tblTransaksiMouseClicked

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        jual p = new jual();
       p.total_harga = String.valueOf(Integer.parseInt(p.harga_satuan) * Integer.parseInt(p.jumlah_barang) -  Integer.parseInt(p.diskon));
        this.inputTotalHarga.setText(String.valueOf(p.total_harga));
    }//GEN-LAST:event_btnhitungActionPerformed

    private void inputTotalHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTotalHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTotalHargaActionPerformed

    private void CheckMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMakananActionPerformed
        inputNamaBarang.setText("Terigu");
        inputKodeBarang.setText("A001");
        inputHargaSatuan.setText("5000");
    }//GEN-LAST:event_CheckMakananActionPerformed

    private void inputJumlahBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputJumlahBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputJumlahBarangActionPerformed

    private void inputJumlahBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputJumlahBarangKeyReleased
             RadioYa.setEnabled(true);
             RadioTidak.setEnabled(true);
    }//GEN-LAST:event_inputJumlahBarangKeyReleased

    private void RadioTidakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioTidakActionPerformed
             jual p = new jual();
      btnhitung.setEnabled(true);
             
      p.diskon = String.valueOf((Integer.parseInt(p.harga_satuan) * Integer.parseInt(p.jumlah_barang))*0);
        inputDiskon.setText(p.diskon);
    }//GEN-LAST:event_RadioTidakActionPerformed

    private void bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bersihkanActionPerformed
          btnhitung.setEnabled(false);
          RadioYa.setEnabled(false);
          RadioTidak.setEnabled(false);
          this.buttonGroup2.clearSelection();
          this.buttonGroup1.clearSelection();
           inputId.setText("");
           inputKodeBarang.setText("");
           inputNamaBarang.setText("");
           inputJumlahBarang.setText("");
           inputHargaSatuan.setText("");
           inputDiskon.setText("");
           inputTotalHarga.setText("");
    }//GEN-LAST:event_bersihkanActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
         jual j = new jual();
        try {       
             stat = k.getCon().prepareStatement("UPDATE tbl_transaksi SET kode_barang=?,"
            + "nama_barang=?,jenis_barang=?,jumlah_barang=?,harga_satuan=?,diskon=?,total_harga=?,member=? WHERE id=?");
            stat.setString(1, inputKodeBarang.getText());
            stat.setString(2,inputNamaBarang.getText());
            stat.setString(3, j.jenis_barang);
            stat.setString(4, inputJumlahBarang.getText());
            stat.setString(5, inputHargaSatuan.getText());
            stat.setString(6,inputDiskon.getText());
            stat.setString(7, inputTotalHarga.getText());
            stat.setString(8, j.member);
            stat.setString(9, inputId.getText());
            stat.executeUpdate();
            refreshTable();
            JOptionPane.showMessageDialog(null, "DATA BERHASIL DI UBAH !");
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(penjual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new penjual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox CheckATK;
    private javax.swing.JCheckBox CheckMakanan;
    private javax.swing.JCheckBox CheckMinuman;
    private javax.swing.JRadioButton RadioTidak;
    private javax.swing.JRadioButton RadioYa;
    private javax.swing.JButton bersihkan;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnhitung;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField inputDiskon;
    private javax.swing.JTextField inputHargaSatuan;
    private javax.swing.JTextField inputId;
    private javax.swing.JTextField inputJumlahBarang;
    private javax.swing.JTextField inputKodeBarang;
    private javax.swing.JTextField inputNamaBarang;
    private javax.swing.JTextField inputTotalHarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTransaksi;
    // End of variables declaration//GEN-END:variables
}
